// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU3yfYvw7pt62IWMKdPS4kHuifdjGMdFk',
    appId: '1:324836527317:web:c472ab36496c050bbba65c',
    messagingSenderId: '324836527317',
    projectId: 'hotel-kitchen-management-73ca7',
    authDomain: 'hotel-kitchen-management-73ca7.firebaseapp.com',
    storageBucket: 'hotel-kitchen-management-73ca7.appspot.com',
    measurementId: 'G-914WBWSPR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzBIxoHQIgnEMcmUosDuS-aN5WYsx9Duc',
    appId: '1:324836527317:android:aa6d9ab393e361d8bba65c',
    messagingSenderId: '324836527317',
    projectId: 'hotel-kitchen-management-73ca7',
    storageBucket: 'hotel-kitchen-management-73ca7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI7Pw-QP3AOReEmS7lzv4oj4hu8yhPAGc',
    appId: '1:324836527317:ios:ba127f307d8d3799bba65c',
    messagingSenderId: '324836527317',
    projectId: 'hotel-kitchen-management-73ca7',
    storageBucket: 'hotel-kitchen-management-73ca7.appspot.com',
    iosBundleId: 'com.example.hotelKitchenManagementFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI7Pw-QP3AOReEmS7lzv4oj4hu8yhPAGc',
    appId: '1:324836527317:ios:f2a6179af33642fcbba65c',
    messagingSenderId: '324836527317',
    projectId: 'hotel-kitchen-management-73ca7',
    storageBucket: 'hotel-kitchen-management-73ca7.appspot.com',
    iosBundleId: 'com.example.hotelKitchenManagementFlutter.RunnerTests',
  );
}
